# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [28]:
from google.colab import files
uploaded = files.upload()

Saving minutes_n_ingredients.csv to minutes_n_ingredients (1).csv


In [29]:
import numpy as np

a = np.loadtxt('minutes_n_ingredients.csv', delimiter = ',', dtype = np.int32 , skiprows = 1 )
print(a[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [30]:
print('среднее значение столбца №2 ', np.mean(a[:, 1]))
print('среднее значение столбца №3 ', np.mean(a[:,2]))
print('минимальное значение столбца №2', np.min(a[:,1]))
print('минимальное значение столбца №3', np.min(a[:,2]))
print('максимальное значение столбца №2', np.max(a[:, 1]))
print('максимальное значение столбца №3', np.max(a[:, 2]))
print('медиана столбца №2 ', np.median(a[:,1]))
print('медиана столбца №3', np.median(a[:,2]))

среднее значение столбца №2  21601.00169
среднее значение столбца №3  9.05528
минимальное значение столбца №2 0
минимальное значение столбца №3 1
максимальное значение столбца №2 2147483647
максимальное значение столбца №3 39
медиана столбца №2  40.0
медиана столбца №3 9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [31]:
b = a.copy()
print(np.count_nonzero(b[:,1]) == 0 )
a [b[:,1] == 0] =1
print(a) 

False
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993    140     14]]


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [32]:

print(np.unique (a[: ,0]))
print(np.unique(a[:,0]).size )

[     1     38     41 ... 537458 537485 537671]
99522


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [33]:
print(np.unique(a[:,2]))
print(np.unique(a[:,2]).size )

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]
37


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [34]:
b = a.copy()
a_a = b[b[:,1] <= 5]
print(a_a)

[[ 67660      5      6]
 [204134      5      3]
 [ 66842      2      4]
 ...
 [420725      5      3]
 [     1      1      1]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [35]:
a = b.copy()
medium = b[:, 2] / b[:,1]
medium.mean(), medium.max()

(0.3429242617056809, 23.0)

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [36]:
a = b.copy()
st = np.argsort(a[:, 1])[-100:]
print(np.mean(a[st][:, 2]))

6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [37]:
b = a.copy()
print(b[np.random.randint(0, b.shape[0], 10)])

[[194075     20     10]
 [ 27394     75     14]
 [222102    435      6]
 [112652     65     12]
 [206780      8      8]
 [455067     25     10]
 [190759    145     12]
 [ 13915     50      8]
 [331996     50     10]
 [ 57929     30     12]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [38]:
a = b.copy()
medium = np.mean(a[:, 2])
print((np.count_nonzero(a[:, 2] < medium) * 100) / a.shape[0])

58.989


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [39]:
a = b.copy()
c = (b[:, 1] <= 20) & (b[:, 2] <= 5).astype(int)
mask_data = np.concatenate((b, c.reshape(1, c.size).T), axis = 1)
print(mask_data)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [41]:
a = b.copy()
simple =  np.count_nonzero(mask_data[:, 3])
print((simple * 100) / b.shape[0])

9.943


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.